//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoISO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListRequirement
    {
        public string Customer_Name { get; set; }
        public string Business_Owner { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string Requirement { get; set; }
        public string Availability { get; set; }
        public int ID_Requirement { get; set; }
    }
}
